global:
  scrape_interval: 5s

scrape_configs:
  - job_name: warehouse-consumer
    metrics_path: /metrics
    static_configs:
      - targets:
          - consumer:8001

rule_files:
  - /etc/prometheus/alerts.yml
